package com.demircandemir.relaysample.ui.theme
import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF396A1E)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFB9F396)
val md_theme_light_onPrimaryContainer = Color(0xFF082100)
val md_theme_light_secondary = Color(0xFF3A6A1D)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFBAF295)
val md_theme_light_onSecondaryContainer = Color(0xFF092100)
val md_theme_light_tertiary = Color(0xFF426915)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFC2F18E)
val md_theme_light_onTertiaryContainer = Color(0xFF0F2000)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFFFBFF)
val md_theme_light_onBackground = Color(0xFF2D1600)
val md_theme_light_surface = Color(0xFFFFFBFF)
val md_theme_light_onSurface = Color(0xFF2D1600)
val md_theme_light_surfaceVariant = Color(0xFFE0E4D6)
val md_theme_light_onSurfaceVariant = Color(0xFF43483E)
val md_theme_light_outline = Color(0xFF74796D)
val md_theme_light_inverseOnSurface = Color(0xFFFFEEE1)
val md_theme_light_inverseSurface = Color(0xFF4B2800)
val md_theme_light_inversePrimary = Color(0xFF9ED67D)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF396A1E)
val md_theme_light_outlineVariant = Color(0xFFC3C8BB)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFF9ED67D)
val md_theme_dark_onPrimary = Color(0xFF133800)
val md_theme_dark_primaryContainer = Color(0xFF215105)
val md_theme_dark_onPrimaryContainer = Color(0xFFB9F396)
val md_theme_dark_secondary = Color(0xFF9FD67B)
val md_theme_dark_onSecondary = Color(0xFF153800)
val md_theme_dark_secondaryContainer = Color(0xFF235104)
val md_theme_dark_onSecondaryContainer = Color(0xFFBAF295)
val md_theme_dark_tertiary = Color(0xFFA7D475)
val md_theme_dark_onTertiary = Color(0xFF1D3700)
val md_theme_dark_tertiaryContainer = Color(0xFF2D5000)
val md_theme_dark_onTertiaryContainer = Color(0xFFC2F18E)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF2D1600)
val md_theme_dark_onBackground = Color(0xFFFFDCC0)
val md_theme_dark_surface = Color(0xFF2D1600)
val md_theme_dark_onSurface = Color(0xFFFFDCC0)
val md_theme_dark_surfaceVariant = Color(0xFF43483E)
val md_theme_dark_onSurfaceVariant = Color(0xFFC3C8BB)
val md_theme_dark_outline = Color(0xFF8D9286)
val md_theme_dark_inverseOnSurface = Color(0xFF2D1600)
val md_theme_dark_inverseSurface = Color(0xFFFFDCC0)
val md_theme_dark_inversePrimary = Color(0xFF396A1E)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFF9ED67D)
val md_theme_dark_outlineVariant = Color(0xFF43483E)
val md_theme_dark_scrim = Color(0xFF000000)


val ShimmerLightGray = Color(0xFFF1F1F1)
val ShimmerMediumGray = Color(0xFFE3E3E3)
val ShimmerDarkGray = Color(0xFF1D1D1D)


val seed = Color(0xFF25530B)
